name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4d367641c1683ded09999a95f6d41427b2dbe7a12346ccbc4d26a9d976d01f7"

[versions]
fabric = "0.17.3"
minecraft = "1.20.2"
