name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5055ec6b9355399c9425aad12edbbcc75dcd98d3c4e661cf78ad1c3296c8175"

[versions]
fabric = "0.17.3"
minecraft = "1.20.5"
