name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7903c0575803b70fa339953105963ca18773059645380ab0ebfe1c68bf7c9940"

[versions]
fabric = "0.17.3"
minecraft = "1.21.5"
