name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0296bbed043d2946eab852b4ea70ef6ebe3f08fd065975c25396ff4f63acecbb"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
