name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "288a8972d3d768fa1198493930ab70d3b14ba0bcb8ff5d76ab783c4c612558db"

[versions]
fabric = "0.17.3"
minecraft = "1.19.3"
