name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "324f4ec987bcb4e6753694d7889b5ea326846d795fcee8caa91f6d02cffdb33d"

[versions]
fabric = "0.17.3"
minecraft = "1.20.6"
