name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3ac9aed0da26ef5a1f86ca75a495c5647007cb97b322f651abb42a3ec7efc32"

[versions]
fabric = "0.17.3"
minecraft = "1.21.9"
