name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec154184fe357010781f9de97f471736e89e2d111d1b1978335b84b8861f9439"

[versions]
fabric = "0.17.3"
minecraft = "1.21.6"
