name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d99bbb98fef8ac8089c3f2646dc1c447790920d6ce9eba8fd37d0dbf5b71be62"

[versions]
fabric = "0.17.3"
minecraft = "1.21"
