name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67647739082f4544e1bcd5d21735da69af507e855f2e4e068e2d6568d65bf69f"

[versions]
fabric = "0.17.3"
minecraft = "1.20.2"
