name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bbed867f15cb02835a65e010d844d3d2122a2345299108ebe6d7a3728a5c0db"

[versions]
fabric = "0.17.3"
minecraft = "1.19.2"
