name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f4c279fa37ac103770c61d05c0e76d0c83dbb88654cb8fd97e5d62295db5af1"

[versions]
fabric = "0.17.3"
minecraft = "1.20.3"
