name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db85e251ad4a5ff25c585398fb00c43e7d891324aeb6b80b4aa1031342f1476f"

[versions]
fabric = "0.17.3"
minecraft = "1.19.3"
