name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "467b5194ca3175e4f66a82cd17bf89af045790d24e77f8b971fd847344b68865"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
