name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e79bf092d483381b8a3e8b143520c22d3de20e1a4b7b9aa5cbb340ab2d36dda6"

[versions]
fabric = "0.17.3"
minecraft = "1.14.1"
