name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d182f7bbe406c64d4cdff56203bff4fc4e19776cfd0885408d9d8e341a56491f"

[versions]
fabric = "0.17.3"
minecraft = "1.15.2"
