name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6549c0c0b2994ad7b98d2ec095f11ee90910ff17bd6eec412e314246e5795364"

[versions]
fabric = "0.17.3"
minecraft = "1.21.7"
