name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4bf0a1744054bf70f17fc35a7b55df8bbafdb6db89b2e406129b3415b70da7a"

[versions]
fabric = "0.17.3"
minecraft = "1.18.2"
