name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fef4afde980e23f6883a494d990495db48e74a222a4446e6b95359bae75875c"

[versions]
fabric = "0.17.3"
minecraft = "1.18.2"
