name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a339d4828a6fd09894ef292454531743b20809ab3ca54a61c723b53afbbee167"

[versions]
fabric = "0.17.3"
minecraft = "1.18.2"
