name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5de6213f216b4a396900ea87a18eab5111426860a14e6d6f74bce6cfbf1b760"

[versions]
fabric = "0.17.3"
minecraft = "1.15.2"
