name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8da1e3c93a6aeb4d4d3b32e31eb8e8c6ae5f29b363ba5346366582bb0e77cb1"

[versions]
fabric = "0.17.3"
minecraft = "1.20"
