name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3923a49a7ccc45e9184011fbe8d6e3ec108fea9a5f95c996c04fc87c78beea"

[versions]
fabric = "0.17.3"
minecraft = "1.19.3"
