name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd8a2e150f8143c7da29be89e00210ee48be2f61b2e9cc9b8c501ba84b3a8468"

[versions]
fabric = "0.17.3"
minecraft = "1.17.1"
