name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe1cb822832a480e637e8a2a6cdef7a8cdc65a02a839c9f8d86658a159012301"

[versions]
fabric = "0.17.3"
minecraft = "1.20.3"
